name: CI

on:
  push:
    branches: [ main ]
    tags:
      - '*'
  pull_request:
    branches: [ main ]

jobs:
  ci:
    name: ci
    runs-on: ubuntu-latest
    steps:
    - name: Clone repo
      uses: actions/checkout@v2
    - name: Set up python
      uses: actions/setup-python@v2
      with:
        python-version: '3.8'
    - name: Install dependencies
      run: pip install -r requirements.txt
    - name: isort
      run: python -m  isort . --check --diff
    - name: black
      run: python -m black --check --diff .
    - name: flake8
      run: python -m flake8 .
    - name: mypy
      run: python -m mypy .
    - name: tests
      run: python -m unittest discover -s tests
    - name: coverage
      run: python -m coverage run -m unittest discover -s tests; python -m coverage report -m
