name: New canary

on:
  workflow_dispatch

jobs:
  new-canary:
    name: New canary
    runs-on: ubuntu-18.04
    steps:
      - name: Clone repo
        uses: actions/checkout@v2
      - name: Set up python
        uses: actions/setup-python@v2
        with:
          python-version: 3.7
      - name: Install dependencies
        run: pip install -r requirements.txt
      - name: Create SSH key
        run: |
          install -m 600 -D /dev/null ~/.ssh/id_rsa
          echo "${{ secrets.SSH_KEY }}" > ~/.ssh/id_rsa
          ssh-keyscan -H fall2022-comp585-5.cs.mcgill.ca > ~/.ssh/known_hosts
      - name: Deploy with mv
        run: |
          git describe --always > models/git_commit.txt
          scp -vv -i ~/.ssh/id_rsa -r models team-5@fall2022-comp585-5.cs.mcgill.ca:~/Team-5/deployed_models/canary
      - name: Update deployment.txt
        run: |
          echo "new_canary,$(date +%s),$(git describe --always)" >> deployments.txt
          python -c "from src.utils.github import GithubClient; client = GithubClient(); client.update_file('deployments.txt', '[AUTOMATED DEPLOYMENT] - New Canary')"
