name: New canary
on:
  push:
    branches:
    - main
    paths:
    - models/model.pt

jobs:
  new-canary:
    name: New canary
    runs-on: ubuntu-18.04
    steps:
      - name: Clone repo
        uses: actions/checkout@v2
      - name: Wait for tests to succeed
        uses: lewagon/wait-on-check-action@v1.2.0
        with:
          ref: ${{ github.ref }}
          check-name: ci
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          wait-interval: 20

      - name: Create SSH key
        run: |
          install -m 600 -D /dev/null ~/.ssh/id_rsa
          echo "${{ secrets.SSH_KEY }}" > ~/.ssh/id_rsa
          ssh-keyscan -H fall2022-comp585-5.cs.mcgill.ca > ~/.ssh/known_hosts
      - name: Deploy with mv
        run: |
          scp -vv -i ~/.ssh/id_rsa -r models team-5@fall2022-comp585-5.cs.mcgill.ca:~/Team-5/deployed_models/canary
          myvar=$(git describe --always)
          ssh -vv team-5@fall2022-comp585-5.cs.mcgill.ca -i ~/.ssh/id_rsa "curl http://localhost:8083/new_model_arrived/$myvar && exit"
      