name: New canary

on:
  workflow_dispatch

jobs:
  new-canary:
    name: New canary
    runs-on: ubuntu-18.04
    steps:
      - name: Create SSH key
        run: |
          install -m 600 -D /dev/null ~/.ssh/id_rsa
          echo "${{ secrets.SSH_KEY }}" > ~/.ssh/id_rsa
      - name: Deploy with mv
        run: |
          scp -i ~/.ssh/id_rsa -r models team-5@fall2022-comp585-5.cs.mcgill.ca:~/Team-5/deployed_models/canary
